
import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author marie
 */
public class graphicalRepresentation extends javax.swing.JPanel {

    /**
     * Creates new form graphicalRepresentation
     */
    public graphicalRepresentation() {
        initComponents();
    }

    //x and width coordinates of gaps (array list of array of two integers: x and width)
    private ArrayList<int[]> xWidthGapCoord = new ArrayList<int[]>();
    private ArrayList<int[]> scaledGapCoord = new ArrayList<int[]>();
    //y coordinate
    private int y = 0;
    private int height = 35;
    
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);

        //N50 and other contigs have different colors
        Color gaps_color = new Color(250, 128, 114);
        Color other_color = new Color(70, 130, 180);

        //Set color and rectangles
        g.setColor(other_color);
        g.fillRect(0, y, this.getWidth(), height);
        
        //For every coordinate, draw a rectangle
        for (int i = 0; i < scaledGapCoord.size(); i++) {
            g.setColor(gaps_color);
            g.fillRect(scaledGapCoord.get(i)[0], y, scaledGapCoord.get(i)[1], height);
            
        }
    }
    
    //Scale width and x
    private void scaleCoord(String sequence){
        //Clear scaled coordinates
        scaledGapCoord.clear();
        double xVal = 0;
        double wVal = 0;
        
        
        //Calculate total length of scaffold
        int scaffLen = sequence.length();
        for(int j = 0; j < xWidthGapCoord.size(); j++){
            int[] coord = new int[2];
            double coef = this.getWidth()/(double)scaffLen;
            //Caclulate new scaled x and width:
            xVal = xWidthGapCoord.get(j)[0]*coef;
            wVal = xWidthGapCoord.get(j)[1]*coef;
            coord[0] = (int)xVal;
            coord[1] = (int)Math.ceil(wVal);
            scaledGapCoord.add(coord);
        }
    }
    

    //Calculate coordinates of gaps rectangles
    private void calculateCoordinates(String sequence) {
        int width = 0;
        int index = 0;
        //Clear array list of coordinates
        xWidthGapCoord.clear();

        //Look for "N" in the sequence
        while (index < sequence.length()) {            
            if(sequence.charAt(index) == ('N')){                
                int[] coord = new int[2];
                coord[0] = index; //Index of first N is x coordinate
                width ++; //One N found
                
                //Check for other successive N to increase the width of the rectangle
                index++;
                while(sequence.charAt(index) == ('N')){
                    width++;
                    index++;
                }
                //No other N found: save width in list of coordinates
                coord[1] = width;
                xWidthGapCoord.add(coord);
            }
            width = 0;
            index++;
        }
        //Scale coordinates
        scaleCoord(sequence);
    }

    //Repaint barplot when fastaFile is given
    public void repaintGraph(String sequence) {
        this.setVisible(true);
        //Calculate coordinates
        calculateCoordinates(sequence);
        //Draw rectangles
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMinimumSize(new java.awt.Dimension(680, 35));
        setPreferredSize(new java.awt.Dimension(680, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
